create table tb_content (text_content varchar(255), video_uri varchar(255), id int8 not null, primary key (id));
create table tb_course (id  bigserial not null, img_gray_uri varchar(255), img_uri varchar(255), name varchar(255), primary key (id));
create table tb_deliver (id  bigserial not null, correct_count int4, feedback varchar(255), moment TIMESTAMP WITHOUT TIME ZONE, status int4, uri varchar(255), offer_id int8, user_id int8, lesson_id int8, primary key (id));
create table tb_enrollment (available boolean not null, enroll_moment TIMESTAMP WITHOUT TIME ZONE, only_update boolean not null, refund_moment TIMESTAMP WITHOUT TIME ZONE, offer_id int8 not null, user_id int8 not null, primary key (offer_id, user_id));
create table tb_lesson (id  bigserial not null, position int4, title varchar(255), section_id int8, primary key (id));
create table tb_lessons_done (lesson_id int8 not null, user_id int8 not null, offer_id int8 not null, primary key (lesson_id, user_id, offer_id));
create table tb_notification (id  bigserial not null, moment TIMESTAMP WITHOUT TIME ZONE, read boolean not null, route varchar(255), text varchar(255), user_id int8, primary key (id));
create table tb_offer (id  bigserial not null, edition varchar(255), end_moment TIMESTAMP WITHOUT TIME ZONE, start_moment TIMESTAMP WITHOUT TIME ZONE, course_id int8, primary key (id));
create table tb_reply (id  bigserial not null, body TEXT, moment TIMESTAMP WITHOUT TIME ZONE, author_id int8, topic_id int8, primary key (id));
create table tb_reply_likes (reply_id int8 not null, user_id int8 not null, primary key (reply_id, user_id));
create table tb_resource (id  bigserial not null, description varchar(255), img_uri varchar(255), position int4, title varchar(255), type int4, offer_id int8, primary key (id));
create table tb_role (id  bigserial not null, authority varchar(255), primary key (id));
create table tb_section (id  bigserial not null, description varchar(255), img_uri varchar(255), position int4, title varchar(255), prerequisite_id int8, resource_id int8, primary key (id));
create table tb_task (approval_count int4, description varchar(255), due_date TIMESTAMP WITHOUT TIME ZONE, question_count int4, weight float8, id int8 not null, primary key (id));
create table tb_topic (id  bigserial not null, body TEXT, moment TIMESTAMP WITHOUT TIME ZONE, title varchar(255), reply_id int8, author_id int8, lesson_id int8, offer_id int8, primary key (id));
create table tb_topic_likes (topic_id int8 not null, user_id int8 not null, primary key (topic_id, user_id));
create table tb_user (id  bigserial not null, email varchar(255), name varchar(255), password varchar(255), primary key (id));
create table tb_user_role (user_id int8 not null, role_id int8 not null, primary key (user_id, role_id));
alter table tb_content add constraint FKjmc1pmpuex5541jwgb07jm4w0 foreign key (id) references tb_lesson;
alter table tb_deliver add constraint FKbv483ch7c1sh53auc1ds0uvi7 foreign key (offer_id, user_id) references tb_enrollment;
alter table tb_deliver add constraint FKjiuhmgjsr90ptlwi820mecyis foreign key (lesson_id) references tb_lesson;
alter table tb_enrollment add constraint FKjtgmmofyyh79cpnndwbohooxg foreign key (offer_id) references tb_offer;
alter table tb_enrollment add constraint FKq4hfr2xc40iew8vo04h7h9s3w foreign key (user_id) references tb_user;
alter table tb_lesson add constraint FKr55u61qpr1cbk0jf474117m1o foreign key (section_id) references tb_section;
alter table tb_lessons_done add constraint FK8d0swyl2ej0ujn2jj1aqn62iy foreign key (user_id, offer_id) references tb_enrollment;
alter table tb_lessons_done add constraint FKfkh2tpm5fahc7mkencew2m529 foreign key (lesson_id) references tb_lesson;
alter table tb_notification add constraint FK9ihj3k9lv33u6qd10wq18f482 foreign key (user_id) references tb_user;
alter table tb_offer add constraint FKetnxqlwav51hu6fxcrukrln2b foreign key (course_id) references tb_course;
alter table tb_reply add constraint FKmac8ai3bigq456vprkpcbbo04 foreign key (author_id) references tb_user;
alter table tb_reply add constraint FK49xc9hx9n1s2cbj4v5nj3pbp2 foreign key (topic_id) references tb_topic;
alter table tb_reply_likes add constraint FK4b9fueljmpwq7mc45sriyyvtw foreign key (user_id) references tb_user;
alter table tb_reply_likes add constraint FKa5dpfalm9mi7ymjo9x0op4c9m foreign key (reply_id) references tb_reply;
alter table tb_resource add constraint FK7py8o9p2xn6jx7um9qb5k421o foreign key (offer_id) references tb_offer;
alter table tb_section add constraint FKng09eguc2o4idipwe73mem9v4 foreign key (prerequisite_id) references tb_section;
alter table tb_section add constraint FKd0pidgdjq979nl3un4ryx5mjx foreign key (resource_id) references tb_resource;
alter table tb_task add constraint FKjpirq3tu0wrko6unh5jx5o39i foreign key (id) references tb_lesson;
alter table tb_topic add constraint FKryr3evgujofa1v0ynultqfqi7 foreign key (reply_id) references tb_reply;
alter table tb_topic add constraint FK3877ei5v3120o8al14nsnu7rr foreign key (author_id) references tb_user;
alter table tb_topic add constraint FKdbxbui164cewmgujgf3yyl0ad foreign key (lesson_id) references tb_lesson;
alter table tb_topic add constraint FKaxi0sbk7u02xr241nv3le3a1x foreign key (offer_id) references tb_offer;
alter table tb_topic_likes add constraint FKfb0wuh6h0tejfujwejutxac1q foreign key (user_id) references tb_user;
alter table tb_topic_likes add constraint FKjyfkg3xwg9v7k8jeijfvlnc7o foreign key (topic_id) references tb_topic;
alter table tb_user_role add constraint FKea2ootw6b6bb0xt3ptl28bymv foreign key (role_id) references tb_role;
alter table tb_user_role add constraint FK7vn3h53d0tqdimm8cp45gc0kl foreign key (user_id) references tb_user;
create table tb_content (text_content varchar(255), video_uri varchar(255), id int8 not null, primary key (id));
create table tb_course (id  bigserial not null, img_gray_uri varchar(255), img_uri varchar(255), name varchar(255), primary key (id));
create table tb_deliver (id  bigserial not null, correct_count int4, feedback varchar(255), moment TIMESTAMP WITHOUT TIME ZONE, status int4, uri varchar(255), offer_id int8, user_id int8, lesson_id int8, primary key (id));
create table tb_enrollment (available boolean not null, enroll_moment TIMESTAMP WITHOUT TIME ZONE, only_update boolean not null, refund_moment TIMESTAMP WITHOUT TIME ZONE, offer_id int8 not null, user_id int8 not null, primary key (offer_id, user_id));
create table tb_lesson (id  bigserial not null, position int4, title varchar(255), section_id int8, primary key (id));
create table tb_lessons_done (lesson_id int8 not null, user_id int8 not null, offer_id int8 not null, primary key (lesson_id, user_id, offer_id));
create table tb_notification (id  bigserial not null, moment TIMESTAMP WITHOUT TIME ZONE, read boolean not null, route varchar(255), text varchar(255), user_id int8, primary key (id));
create table tb_offer (id  bigserial not null, edition varchar(255), end_moment TIMESTAMP WITHOUT TIME ZONE, start_moment TIMESTAMP WITHOUT TIME ZONE, course_id int8, primary key (id));
create table tb_reply (id  bigserial not null, body TEXT, moment TIMESTAMP WITHOUT TIME ZONE, author_id int8, topic_id int8, primary key (id));
create table tb_reply_likes (reply_id int8 not null, user_id int8 not null, primary key (reply_id, user_id));
create table tb_resource (id  bigserial not null, description varchar(255), img_uri varchar(255), position int4, title varchar(255), type int4, offer_id int8, primary key (id));
create table tb_role (id  bigserial not null, authority varchar(255), primary key (id));
create table tb_section (id  bigserial not null, description varchar(255), img_uri varchar(255), position int4, title varchar(255), prerequisite_id int8, resource_id int8, primary key (id));
create table tb_task (approval_count int4, description varchar(255), due_date TIMESTAMP WITHOUT TIME ZONE, question_count int4, weight float8, id int8 not null, primary key (id));
create table tb_topic (id  bigserial not null, body TEXT, moment TIMESTAMP WITHOUT TIME ZONE, title varchar(255), reply_id int8, author_id int8, lesson_id int8, offer_id int8, primary key (id));
create table tb_topic_likes (topic_id int8 not null, user_id int8 not null, primary key (topic_id, user_id));
create table tb_user (id  bigserial not null, email varchar(255), name varchar(255), password varchar(255), primary key (id));
create table tb_user_role (user_id int8 not null, role_id int8 not null, primary key (user_id, role_id));
alter table tb_content add constraint FKjmc1pmpuex5541jwgb07jm4w0 foreign key (id) references tb_lesson;
alter table tb_deliver add constraint FKbv483ch7c1sh53auc1ds0uvi7 foreign key (offer_id, user_id) references tb_enrollment;
alter table tb_deliver add constraint FKjiuhmgjsr90ptlwi820mecyis foreign key (lesson_id) references tb_lesson;
alter table tb_enrollment add constraint FKjtgmmofyyh79cpnndwbohooxg foreign key (offer_id) references tb_offer;
alter table tb_enrollment add constraint FKq4hfr2xc40iew8vo04h7h9s3w foreign key (user_id) references tb_user;
alter table tb_lesson add constraint FKr55u61qpr1cbk0jf474117m1o foreign key (section_id) references tb_section;
alter table tb_lessons_done add constraint FK8d0swyl2ej0ujn2jj1aqn62iy foreign key (user_id, offer_id) references tb_enrollment;
alter table tb_lessons_done add constraint FKfkh2tpm5fahc7mkencew2m529 foreign key (lesson_id) references tb_lesson;
alter table tb_notification add constraint FK9ihj3k9lv33u6qd10wq18f482 foreign key (user_id) references tb_user;
alter table tb_offer add constraint FKetnxqlwav51hu6fxcrukrln2b foreign key (course_id) references tb_course;
alter table tb_reply add constraint FKmac8ai3bigq456vprkpcbbo04 foreign key (author_id) references tb_user;
alter table tb_reply add constraint FK49xc9hx9n1s2cbj4v5nj3pbp2 foreign key (topic_id) references tb_topic;
alter table tb_reply_likes add constraint FK4b9fueljmpwq7mc45sriyyvtw foreign key (user_id) references tb_user;
alter table tb_reply_likes add constraint FKa5dpfalm9mi7ymjo9x0op4c9m foreign key (reply_id) references tb_reply;
alter table tb_resource add constraint FK7py8o9p2xn6jx7um9qb5k421o foreign key (offer_id) references tb_offer;
alter table tb_section add constraint FKng09eguc2o4idipwe73mem9v4 foreign key (prerequisite_id) references tb_section;
alter table tb_section add constraint FKd0pidgdjq979nl3un4ryx5mjx foreign key (resource_id) references tb_resource;
alter table tb_task add constraint FKjpirq3tu0wrko6unh5jx5o39i foreign key (id) references tb_lesson;
alter table tb_topic add constraint FKryr3evgujofa1v0ynultqfqi7 foreign key (reply_id) references tb_reply;
alter table tb_topic add constraint FK3877ei5v3120o8al14nsnu7rr foreign key (author_id) references tb_user;
alter table tb_topic add constraint FKdbxbui164cewmgujgf3yyl0ad foreign key (lesson_id) references tb_lesson;
alter table tb_topic add constraint FKaxi0sbk7u02xr241nv3le3a1x foreign key (offer_id) references tb_offer;
alter table tb_topic_likes add constraint FKfb0wuh6h0tejfujwejutxac1q foreign key (user_id) references tb_user;
alter table tb_topic_likes add constraint FKjyfkg3xwg9v7k8jeijfvlnc7o foreign key (topic_id) references tb_topic;
alter table tb_user_role add constraint FKea2ootw6b6bb0xt3ptl28bymv foreign key (role_id) references tb_role;
alter table tb_user_role add constraint FK7vn3h53d0tqdimm8cp45gc0kl foreign key (user_id) references tb_user;
create table tb_content (text_content varchar(255), video_uri varchar(255), id int8 not null, primary key (id));
create table tb_course (id  bigserial not null, img_gray_uri varchar(255), img_uri varchar(255), name varchar(255), primary key (id));
create table tb_deliver (id  bigserial not null, correct_count int4, feedback varchar(255), moment TIMESTAMP WITHOUT TIME ZONE, status int4, uri varchar(255), offer_id int8, user_id int8, lesson_id int8, primary key (id));
create table tb_enrollment (available boolean not null, enroll_moment TIMESTAMP WITHOUT TIME ZONE, only_update boolean not null, refund_moment TIMESTAMP WITHOUT TIME ZONE, offer_id int8 not null, user_id int8 not null, primary key (offer_id, user_id));
create table tb_lesson (id  bigserial not null, position int4, title varchar(255), section_id int8, primary key (id));
create table tb_lessons_done (lesson_id int8 not null, user_id int8 not null, offer_id int8 not null, primary key (lesson_id, user_id, offer_id));
create table tb_notification (id  bigserial not null, moment TIMESTAMP WITHOUT TIME ZONE, read boolean not null, route varchar(255), text varchar(255), user_id int8, primary key (id));
create table tb_offer (id  bigserial not null, edition varchar(255), end_moment TIMESTAMP WITHOUT TIME ZONE, start_moment TIMESTAMP WITHOUT TIME ZONE, course_id int8, primary key (id));
create table tb_reply (id  bigserial not null, body TEXT, moment TIMESTAMP WITHOUT TIME ZONE, author_id int8, topic_id int8, primary key (id));
create table tb_reply_likes (reply_id int8 not null, user_id int8 not null, primary key (reply_id, user_id));
create table tb_resource (id  bigserial not null, description varchar(255), img_uri varchar(255), position int4, title varchar(255), type int4, offer_id int8, primary key (id));
create table tb_role (id  bigserial not null, authority varchar(255), primary key (id));
create table tb_section (id  bigserial not null, description varchar(255), img_uri varchar(255), position int4, title varchar(255), prerequisite_id int8, resource_id int8, primary key (id));
create table tb_task (approval_count int4, description varchar(255), due_date TIMESTAMP WITHOUT TIME ZONE, question_count int4, weight float8, id int8 not null, primary key (id));
create table tb_topic (id  bigserial not null, body TEXT, moment TIMESTAMP WITHOUT TIME ZONE, title varchar(255), reply_id int8, author_id int8, lesson_id int8, offer_id int8, primary key (id));
create table tb_topic_likes (topic_id int8 not null, user_id int8 not null, primary key (topic_id, user_id));
create table tb_user (id  bigserial not null, email varchar(255), name varchar(255), password varchar(255), primary key (id));
create table tb_user_role (user_id int8 not null, role_id int8 not null, primary key (user_id, role_id));
alter table tb_content add constraint FKjmc1pmpuex5541jwgb07jm4w0 foreign key (id) references tb_lesson;
alter table tb_deliver add constraint FKbv483ch7c1sh53auc1ds0uvi7 foreign key (offer_id, user_id) references tb_enrollment;
alter table tb_deliver add constraint FKjiuhmgjsr90ptlwi820mecyis foreign key (lesson_id) references tb_lesson;
alter table tb_enrollment add constraint FKjtgmmofyyh79cpnndwbohooxg foreign key (offer_id) references tb_offer;
alter table tb_enrollment add constraint FKq4hfr2xc40iew8vo04h7h9s3w foreign key (user_id) references tb_user;
alter table tb_lesson add constraint FKr55u61qpr1cbk0jf474117m1o foreign key (section_id) references tb_section;
alter table tb_lessons_done add constraint FK8d0swyl2ej0ujn2jj1aqn62iy foreign key (user_id, offer_id) references tb_enrollment;
alter table tb_lessons_done add constraint FKfkh2tpm5fahc7mkencew2m529 foreign key (lesson_id) references tb_lesson;
alter table tb_notification add constraint FK9ihj3k9lv33u6qd10wq18f482 foreign key (user_id) references tb_user;
alter table tb_offer add constraint FKetnxqlwav51hu6fxcrukrln2b foreign key (course_id) references tb_course;
alter table tb_reply add constraint FKmac8ai3bigq456vprkpcbbo04 foreign key (author_id) references tb_user;
alter table tb_reply add constraint FK49xc9hx9n1s2cbj4v5nj3pbp2 foreign key (topic_id) references tb_topic;
alter table tb_reply_likes add constraint FK4b9fueljmpwq7mc45sriyyvtw foreign key (user_id) references tb_user;
alter table tb_reply_likes add constraint FKa5dpfalm9mi7ymjo9x0op4c9m foreign key (reply_id) references tb_reply;
alter table tb_resource add constraint FK7py8o9p2xn6jx7um9qb5k421o foreign key (offer_id) references tb_offer;
alter table tb_section add constraint FKng09eguc2o4idipwe73mem9v4 foreign key (prerequisite_id) references tb_section;
alter table tb_section add constraint FKd0pidgdjq979nl3un4ryx5mjx foreign key (resource_id) references tb_resource;
alter table tb_task add constraint FKjpirq3tu0wrko6unh5jx5o39i foreign key (id) references tb_lesson;
alter table tb_topic add constraint FKryr3evgujofa1v0ynultqfqi7 foreign key (reply_id) references tb_reply;
alter table tb_topic add constraint FK3877ei5v3120o8al14nsnu7rr foreign key (author_id) references tb_user;
alter table tb_topic add constraint FKdbxbui164cewmgujgf3yyl0ad foreign key (lesson_id) references tb_lesson;
alter table tb_topic add constraint FKaxi0sbk7u02xr241nv3le3a1x foreign key (offer_id) references tb_offer;
alter table tb_topic_likes add constraint FKfb0wuh6h0tejfujwejutxac1q foreign key (user_id) references tb_user;
alter table tb_topic_likes add constraint FKjyfkg3xwg9v7k8jeijfvlnc7o foreign key (topic_id) references tb_topic;
alter table tb_user_role add constraint FKea2ootw6b6bb0xt3ptl28bymv foreign key (role_id) references tb_role;
alter table tb_user_role add constraint FK7vn3h53d0tqdimm8cp45gc0kl foreign key (user_id) references tb_user;
