version: "3.7"
services:
  dscatalog:
    container_name: postgres_dscatalog
    image: postgres:12.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"